/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import checkassgment.checkvalidate;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.AEADBadTagException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DAOsinhviendiem;
import model.DBconnect;
import model.SinhVienDAO;
import model.UserDAO;
import model.sinhviendiem;

/**
 *
 * @author Admin
 */
public class QLSV1 extends javax.swing.JFrame {

    String head[] = {"Mã sv", "Họ Tên ", "Tiếng Anh", "Tin Học", "GDTC", "Điểm TB"};
    DefaultTableModel model = new DefaultTableModel(head, 0);
    Connection con;
    DAOsinhviendiem _dao = new DAOsinhviendiem();
    List<sinhviendiem> ls = new ArrayList();
    int curent = 0;

    /**
     * Creates new form QLSV1
     */
    public QLSV1() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            con = DBconnect.getconnect("assignment");
//            if(con != null){
//                System.out.println("xxx");
//            }
        } catch (Exception e) {
        }
        loadtable();
        TableList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSeach = new javax.swing.JTextField();
        btnseach = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        txttienganh = new javax.swing.JTextField();
        txttinhoc = new javax.swing.JTextField();
        txtgdtc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbldiem = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnprx2 = new javax.swing.JButton();
        btnpr = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnnext2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Tìm kiếm ");

        btnseach.setForeground(new java.awt.Color(51, 0, 255));
        btnseach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnseach.setText("Seach");
        btnseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnseach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnseach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel3.setText("Họ Tên Sv");

        jLabel5.setText("Mã SV");

        jLabel6.setText("Tiếng Anh");

        jLabel7.setText("Tin học");

        jLabel8.setText("Giáo dục TC");

        jLabel9.setText("Điểm TB");

        lbldiem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldiem.setForeground(new java.awt.Color(0, 0, 255));
        lbldiem.setText("9.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfullname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttinhoc, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txttienganh)
                            .addComponent(txtmasv)
                            .addComponent(txtgdtc))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttienganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttinhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(lbldiem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgdtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26))
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        btnnew.setForeground(new java.awt.Color(0, 0, 255));
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel3.add(btnnew);

        btnsave.setForeground(new java.awt.Color(0, 0, 255));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave);

        btndelete.setForeground(new java.awt.Color(0, 51, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete);

        btnupdate.setForeground(new java.awt.Color(0, 51, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        btnprx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprx2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnprx2);

        btnpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Left.png"))); // NOI18N
        btnpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprActionPerformed(evt);
            }
        });
        jPanel4.add(btnpr);

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Right.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        jPanel4.add(btnnext);

        btnnext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnext2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnnext2);

        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên ", "Tiếng Anh", "Tin Học", "Giáo dục thể chất", "điểm TB"
            }
        ));
        TableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableList);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("3 Sinh viên có điểm cao nhất  :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListMouseClicked
        // TODO add your handling code here:
        int row = TableList.getSelectedRow();
        if (row >= 0) {
            txtfullname.setText(TableList.getValueAt(row, 1).toString());
            txtmasv.setText(TableList.getValueAt(row, 0).toString());
            txttienganh.setText(TableList.getValueAt(row, 2).toString());
            txttinhoc.setText(TableList.getValueAt(row, 3).toString());
            txtgdtc.setText(TableList.getValueAt(row, 4).toString());
            lbldiem.setText(TableList.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_TableListMouseClicked

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        txtgdtc.setText("");
        txtmasv.setText("");
        txttienganh.setText("");
        txttinhoc.setText("");
        txtfullname.setText("");
        lbldiem.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        checkvalidate check = new checkvalidate();
        checkrong();
        try {
            checknumber();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e + " lỗi");
        }
        String sql = " insert into sinhvien (hoten,masv,tienganh,tinhoc,gdtc)\n"
                + "values(?,?,?,?,?)";
        Float ta = Float.parseFloat(txttienganh.getText());
        Float tin = Float.parseFloat(txttinhoc.getText());
        Float gdtc = Float.parseFloat(txtgdtc.getText());
        try {
            Connection Con = DBconnect.getconnect("assignment");
            PreparedStatement pstm = Con.prepareStatement(sql);
            pstm.setString(1, txtfullname.getText());
            pstm.setString(2, txtmasv.getText());
            pstm.setFloat(3, ta);
            pstm.setFloat(4, tin);
            pstm.setFloat(5, gdtc);
           
            model.addRow(new Object[]{txtmasv.getText().trim(), txtfullname.getText().trim(), ta, tin, gdtc, (ta + tin + gdtc) / 3});
            try {
                int i = pstm.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "thêm vào csdl thành công !");
                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("loi");
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(" lỗi");
        }
        model.setRowCount(0);
        loadtable();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseachActionPerformed
//  DAOsinhviendiem dao = new DAOsinhviendiem();
//  dao.Find(txtSeach.getText());
StringBuilder sb = new StringBuilder();
        for (sinhviendiem x : ls) {
            System.out.println(x);
            if (x.getMasv().trim().equals(txtSeach.getText().trim())) {
                txtfullname.setText(x.getHoten());
                txtgdtc.setText(x.getGdtc() + "");
                txtmasv.setText(x.getMasv());
                txttienganh.setText(x.getTienganh() + "");
                txttinhoc.setText(x.getTinhoc() + "");
                JOptionPane.showMessageDialog(this, x.toString());
                return;
            } 
             if (!x.getMasv().trim().equals(txtSeach.getText().trim())) {
//                JOptionPane.showMessageDialog(this, "không tìm thấy sinh viên");   
                sb.append("không tìm thấy sinh viên \n");
            }
        }
if(sb != null){
 JOptionPane.showMessageDialog(this, "không tìm thấy sinh viên \n");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnseachActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String sql = "delete from sinhvien where masv = ?";
        for (sinhviendiem x : ls) {
            if (x.getMasv().equals(txtSeach.getText())) {
                try {
                    PreparedStatement pstm = con.prepareStatement(sql);
                    pstm.setString(1, txtmasv.getText());
                    int i = pstm.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(this, "đã xóa thành công !");
                    } else {
                        JOptionPane.showMessageDialog(this, "xóa thất bại ");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    Logger.getLogger(QLSV1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        model.setRowCount(0);
        loadtable();

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String sql = "update  sinhvien set hoten = ? ,tienganh = ? ,tinhoc = ? ,gdtc = ? where masv  = ?";
        for (sinhviendiem x : ls) {
            try {
                PreparedStatement pstm = con.prepareStatement(sql);
                pstm.setString(1, txtfullname.getText());
                pstm.setFloat(2, Float.parseFloat(txttienganh.getText()));
                pstm.setFloat(3, Float.parseFloat(txttinhoc.getText()));
                pstm.setFloat(4, Float.parseFloat(txtgdtc.getText()));
                pstm.setString(5, txtmasv.getText());
                int i = pstm.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "đã update thành công ");
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "không thành công ");

                }
            } catch (SQLException ex) {
                Logger.getLogger(QLSV1.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        model.setRowCount(0);
        loadtable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        curent++;
        if (curent >= ls.size()) {
            JOptionPane.showMessageDialog(this, "đang ở cuối danh sách \n hết list dể next");
            return;
        }

        display(curent);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnnext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnext2ActionPerformed
        curent = ls.size() - 1;
        display(curent);        // TODO add your handling code here:
    }//GEN-LAST:event_btnnext2ActionPerformed

    private void btnprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprActionPerformed
        curent--;
        if (curent < 0) {
            JOptionPane.showMessageDialog(this, "đang ở đầu danh sách \n hết list dể back");
            return;
        }

        display(curent);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprActionPerformed

    private void btnprx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprx2ActionPerformed
        curent = 0;
        display(curent);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprx2ActionPerformed
    public void checkrong() {
        checkvalidate check = new checkvalidate();
        StringBuilder sb = new StringBuilder();
        if (!check.checkemty(txtmasv.getText())) {
            sb.append("Mã sinh viên không được bỏ trống ! \n");
            txtmasv.setBackground(Color.red);
        } else {
            txtmasv.setBackground(Color.white);
        }
        if (!check.checkemty(txttienganh.getText())) {
            sb.append("điểm tiếng anh  sinh viên không được bỏ trống ! \n");
            txttienganh.setBackground(Color.red);
        } else {
            txttienganh.setBackground(Color.white);
        }
        if (!check.checkemty(txttinhoc.getText())) {
            sb.append("điểm tin học sinh viên không được bỏ trống ! \n");
            txttinhoc.setBackground(Color.red);
        } else {
            txttinhoc.setBackground(Color.white);
        }
        if (!check.checkemty(txtgdtc.getText())) {
            sb.append("điểm GDTC sinh viên không được bỏ trống ! \n");
            txtgdtc.setBackground(Color.red);
        } else {
            txtgdtc.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
        }
    }

    public void checknumber() {
        checkvalidate check = new checkvalidate();
        StringBuilder sb3 = new StringBuilder();
        StringBuilder sb2 = new StringBuilder();
        try {
            Float tienganh = Float.parseFloat(txttienganh.getText());
            if (tienganh > 10 || tienganh < 0) {
                sb3.append("Điểm phải nằm trong khoảng từ 0 -10");
            }
            tienganh = Float.parseFloat(txttienganh.getText());
        } catch (Exception e) {
            sb2.append("điểm tiếng anh phải nhập bằng số ! \n");
        }
        try {
            Float tin = Float.parseFloat(txttinhoc.getText());
            if (tin > 10 || tin < 0) {
                sb3.append("Điểm phải nằm trong khoảng từ 0 -10");
            }
            tin = Float.parseFloat(txttinhoc.getText());
        } catch (Exception e) {
            sb2.append("điểm tin học  phải nhập bằng số ! \n");
        }
        try {
            Float gdtc = Float.parseFloat(txtgdtc.getText());
            if (gdtc > 10 || gdtc < 0) {
                sb3.append("Điểm phải nằm trong khoảng từ 0 -10");
            }
            gdtc = Float.parseFloat(txtgdtc.getText());
        } catch (Exception e) {
            sb2.append("điểm GDTC  phải nhập bằng số ! \n");
        }
        if (sb2.length() > 0) {
            JOptionPane.showMessageDialog(this, sb2);
        }
        if (sb3.length() > 0) {
            JOptionPane.showMessageDialog(this, sb3);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV1().setVisible(true);
            }
        });
    }

    public void loadtable() {
        String sql = "select * from sinhvien";

        try (
                 Statement stm = con.createStatement();  ResultSet rs = stm.executeQuery(sql);) {
            model.setRowCount(0);
            while (rs.next()) {
                String hoten = rs.getString(1);
                String masv = rs.getString(2);
                Float tienganh = Float.parseFloat(rs.getString(3));
                Float tinhoc = Float.parseFloat(rs.getString(4));
                Float gdtc = Float.parseFloat(rs.getString(5));
                Float diemtb = (tienganh + tinhoc + gdtc) / 3;
                sinhviendiem sv = new sinhviendiem(masv, hoten, tienganh, tinhoc, gdtc);
                ls.add(sv);
                model.addRow(new Object[]{masv, hoten, tienganh, tinhoc, gdtc, diemtb});
//               TableList.setModel(model);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public List<sinhviendiem> loaddata() {
        String sql = "select * from sinhvien";

        try (
                 Statement stm = con.createStatement();  ResultSet rs = stm.executeQuery(sql);) {
            model.setRowCount(0);
            while (rs.next()) {
                String hoten = rs.getString(1);
                String masv = rs.getString(2);
                Float tienganh = Float.parseFloat(rs.getString(3));
                Float tinhoc = Float.parseFloat(rs.getString(4));
                Float gdtc = Float.parseFloat(rs.getString(5));
                Float diemtb = (tienganh + tinhoc + gdtc) / 3;
                sinhviendiem sv = new sinhviendiem(masv, hoten, tienganh, tinhoc, gdtc);
                ls.add(sv);
                return ls;
//                model.addRow(new Object[]{masv, hoten, tienganh, tinhoc, gdtc, diemtb});
//               TableList.setModel(model);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserDAO.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableList;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnnext2;
    private javax.swing.JButton btnpr;
    private javax.swing.JButton btnprx2;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnseach;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldiem;
    private javax.swing.JTextField txtSeach;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtgdtc;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txttienganh;
    private javax.swing.JTextField txttinhoc;
    // End of variables declaration//GEN-END:variables

    private void display(int i) {
        sinhviendiem sv = ls.get(i);
        txtfullname.setText(sv.getHoten());
        txtmasv.setText(sv.getMasv());
        txttienganh.setText(sv.getTienganh() + "");
        txttinhoc.setText(sv.getTinhoc() + "");
        txtgdtc.setText(sv.getGdtc() + "");

    }

}
